name: Order Tests
on:
  pull_request:
    paths:
      - "order/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Order Service Tests
        run: cd order && npm install && npm run test:ci
