name: Payments Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Payments Service Tests
        run: cd payment && npm install && npm run test:ci
