name: Test
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - uses: actions/checkout@v2
    - name: Auth Service Tests
      run: cd auth && npm install && npm run test:ci
