name: Ticket Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ticket Service Tests
        run: cd ticket && npm install && npm run test:ci
