name: Ticket Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: getong/mariadb-action@v1.1
      with:
        mariadb version: '10.4.10'
        mysql database: 'tickets'
        mysql root password: ${{ secrets.RootPassword }}
      - uses: actions/checkout@v2
      - name: Ticket Service Tests
        run: cd ticket && npm install && npm run test:ci
